### ISSUE TITLE
Make all images for clean architecture chapters smaller if too big

### ISSUE THREAD

**Issue by preslavmihaylov** [preslavmihaylov/booknotes#1]
There are instances of images which are too big because markdown stretches them by default.

Find all such instances and use regular HTML to limit the width of the pictures in order for them to look better.

**Comment by palakdavda22** [comment]
Can you provide one file name in which the size of image is big, for better understanding?

**Comment by preslavmihaylov** [comment]
One type of problem is that often times, images appear on the same line as the previous row as in [here](https://github.com/preslavmihaylov/booknotes/tree/master/architecture/clean-architecture/part-5#plugin-architecture):
![image](https://user-images.githubusercontent.com/7642330/96966619-c98f2f00-1516-11eb-8c09-17a0217f9e8c.png)

This can be fixed by putting a whitespace between the picture and the line before it.

Another problem is that often times, some images are rendered too big by default. [example](https://github.com/preslavmihaylov/booknotes/tree/master/architecture/clean-architecture/part-5#the-dreaded-monolith):
![image](https://user-images.githubusercontent.com/7642330/96966674-e9beee00-1516-11eb-9940-b7658e44111a.png)

**Comment by Hassan-Elseoudy** [comment]
I'm into it, May i be assigned this one @preslavmihaylov ?

**Comment by preslavmihaylov** [comment]
sure, you're good to go

**Comment by preslavmihaylov** [comment]
I will also accept pull requests for the same task but for the java concurrency in practice book

**Comment by Hassan-Elseoudy** [comment]
Waiting for review :) @preslavmihaylov

**Comment by preslavmihaylov** [comment]
Solved in #4
