### ISSUE TITLE
Make all images for Java Concurrency chapters smaller if too big

### ISSUE THREAD

**Issue by preslavmihaylov** [preslavmihaylov/booknotes#5]
One type of problem is that often times, images appear on the same line as the previous row as in [here](https://github.com/preslavmihaylov/booknotes/tree/master/architecture/clean-architecture/part-5#plugin-architecture):
![image](https://user-images.githubusercontent.com/7642330/96966619-c98f2f00-1516-11eb-8c09-17a0217f9e8c.png)

This can be fixed by putting a whitespace between the picture and the line before it.

Another problem is that often times, some images are rendered too big by default. [example](https://github.com/preslavmihaylov/booknotes/tree/master/architecture/clean-architecture/part-5#the-dreaded-monolith):
![image](https://user-images.githubusercontent.com/7642330/96966674-e9beee00-1516-11eb-9940-b7658e44111a.png)

I think this one can be reduced to be at most 300 pixels wide

**Comment by ved-asole** [comment]
Hi @preslavmihaylov, let me know if I can take care of the above issue.

**Comment by preslavmihaylov** [comment]
of course, please go ahead!
