### ISSUE TITLE
Eisenhower's Matrix needs numbers

### ISSUE THREAD

**Issue by abulka** [preslavmihaylov/booknotes#6]
The discussion re Eisenhower's Matrix in the intro chapter refers to quadrants 1-4, without specifying which quadrants represent which number. This makes it impossible to follow that part of the discussion.

**Comment by preslavmihaylov** [comment]
@abulka thanks for flagging this!

I've updated that section. Can you check if it makes more sense now? 
https://github.com/preslavmihaylov/booknotes/blob/master/architecture/clean-architecture/part-1/README.md#eisenhowers-matrix

**Comment by preslavmihaylov** [comment]
Yeah, this enumeration of quadrants [comes from geometry](https://en.wikipedia.org/wiki/Quadrant_(plane_geometry)).
